
  
substitutions:
  _SERVICE_DIR: services
  _SERVICE_NAME: dbt-service

steps:

  - id: "dbt-image"
    name: "gcr.io/cloud-builders/docker"
    args: ["build","-t","gcr.io/${PROJECT_ID}/${_SERVICE_NAME}","${_SERVICE_DIR}/${_SERVICE_NAME}/."]

  - id: "push dbt-image"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}"]
    wait_for: ['dbt-image']

images:
  - "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}"