main_profile:
  outputs:
    staging:
      dataset: staging
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: EU
      method: oauth
      priority: interactive
      project: datachecker-test
      threads: 4
      type: bigquery
  target: staging
