name: Push image to GCR

on:
  push:
    branches:
      - gitactions
      - master

env:
  IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/dbt-service
  DOCKERFILE_PATH: ./services/dbt-service/Dockerfile
  GCS_BUCKET: ${{ secrets.GCP_PROJECT_ID }}-dbt-service
  GCS_DESTINATION: my-folder

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Google Cloud SDK
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}

      - name: Copy to GCS
        uses: google-github-actions/upload-cloud-storage@master
        with:
          source: ./service/dbt-service/profiles
          destination: gs://${{ env.GCS_BUCKET }}/
          credentials: ${{ secrets.GCP_SA_KEY }}